name: CI/BUILD
on:
  push:
    branches: ['**']
  pull_request:
    branches: [ main, development ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x', cache: true, cache-dependency-path: '**/*.csproj' }
      - run: dotnet restore Taskflow.API.sln
      - run: dotnet build Taskflow.API.sln -c Release --no-restore
